package com.dhw.greendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.dhw.greendao.bean.FirstBean;
import com.dhw.greendao.bean.NewslistBean;
import com.dhw.greendao.bean.SecondBean;

import com.dhw.greendao.dao.FirstBeanDao;
import com.dhw.greendao.dao.NewslistBeanDao;
import com.dhw.greendao.dao.SecondBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig firstBeanDaoConfig;
    private final DaoConfig newslistBeanDaoConfig;
    private final DaoConfig secondBeanDaoConfig;

    private final FirstBeanDao firstBeanDao;
    private final NewslistBeanDao newslistBeanDao;
    private final SecondBeanDao secondBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        firstBeanDaoConfig = daoConfigMap.get(FirstBeanDao.class).clone();
        firstBeanDaoConfig.initIdentityScope(type);

        newslistBeanDaoConfig = daoConfigMap.get(NewslistBeanDao.class).clone();
        newslistBeanDaoConfig.initIdentityScope(type);

        secondBeanDaoConfig = daoConfigMap.get(SecondBeanDao.class).clone();
        secondBeanDaoConfig.initIdentityScope(type);

        firstBeanDao = new FirstBeanDao(firstBeanDaoConfig, this);
        newslistBeanDao = new NewslistBeanDao(newslistBeanDaoConfig, this);
        secondBeanDao = new SecondBeanDao(secondBeanDaoConfig, this);

        registerDao(FirstBean.class, firstBeanDao);
        registerDao(NewslistBean.class, newslistBeanDao);
        registerDao(SecondBean.class, secondBeanDao);
    }
    
    public void clear() {
        firstBeanDaoConfig.clearIdentityScope();
        newslistBeanDaoConfig.clearIdentityScope();
        secondBeanDaoConfig.clearIdentityScope();
    }

    public FirstBeanDao getFirstBeanDao() {
        return firstBeanDao;
    }

    public NewslistBeanDao getNewslistBeanDao() {
        return newslistBeanDao;
    }

    public SecondBeanDao getSecondBeanDao() {
        return secondBeanDao;
    }

}
